### ISSUE TITLE
Unable to customize markers in cluster

### ISSUE THREAD

**Issue by rohitvipin** [streinhard/Xamarin.Google.iOS.Maps.Utility#2]
Unable to extend GMUDefaultClusterRenderer and override this method

```
(GMSMarker *)markerWithPosition:(CLLocationCoordinate2D)position
                             from:(CLLocationCoordinate2D)from
                         userData:(id)userData
                      clusterIcon:(UIImage *)clusterIcon
                         animated:(BOOL)animated
```

https://github.com/googlemaps/google-maps-ios-utils/issues/21
https://github.com/googlemaps/google-maps-ios-utils/issues/38

**Comment by streinhard** [comment]
I guess your question is how to achieve the same with this binding?

Well, I can point you in some directions, but you'll have to figure out the details yourself. The Objective-C signature you posted is no longer present in the Google iOS utility library. There seems to be [a new way to do this](https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md). 

You can create a custom cluster renderer by overrriding `ClusterRendererDelegate`. Here's some example code:

```
public class CustomMarkerRender : ClusterRendererDelegate
{
    public override void WillRenderMarker(ClusterRenderer renderer, Marker marker)
    {
        // Your code here
    }

    public override void DidRenderMarker(ClusterRenderer renderer, Marker marker)
    {
        // Your code here;
    }
}

public class Example
{

    private void InitClustering()
    {
        // ...
        var renderer = new DefaultClusterRenderer(mapView, iconGenerator);

        renderer.Delegate = new CustomMarkerRender();
    }
}
```

[Here is a Objective-C based implementation ](https://github.com/googlemaps/google-maps-ios-utils/blob/master/app/CustomMarkerViewController.m) of a custom marker renderer. You'll have to translate its behaviour into C#.

If you are successful doing so, it would be nice if you could share your result here, others might have the same question. Maybe I can even add it as an example with your permission.
